# Stage 1: Build the application
FROM node:20.11.1 AS builder

WORKDIR /app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Next.js application
RUN npm run build

# Stage 2: Run the application
FROM node:20.11.1

WORKDIR /app

# Copy the build output from the builder stage
COPY --from=builder /app ./

# Install production dependencies
RUN npm ci --only=production

# Expose the port
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start"]
